#!/bin/bash

var1="A"
var2="B"

mi_funcion () {
    local var1="C"
    var2="D"
    echo "Dentro de la función: var1: $var1, var2: $var2"
}

echo "Antes de ejecutar la función: var1: $var1, var2: $var2"

mi_funcion

echo "Despues de la función: var1: $var1, var2: $var2"

