#!/bin/bash

if [ -e $HOME ]
then
    echo "OK en el directorio, ahora vamos a validar el archivo"
    if [ -e $HOME/testing ]
    then
        echo "Adicionando informacion al archivo"
	date >> $HOME/testing
    else
        echo "Creando el archivo"
	date > $HOME/testing
    fi
else
    echo "Hay un problema con el directorio HOME"
fi

